---
title: Bouw je eigen wereld
hero_image: images/banner.png
description: Ontwerp en bouw een 3D wereld met interessante landschappen en functies met een personage naar keuze
meta_title: Leer Unity | Games ontwikkelen | Bouw je eigen wereld
meta_description: Leer Unity-gameontwikkeling met de Raspberry Pi Foundation. Gebruik je Unity-vaardigheden om een 3D-wereld te ontwerpen en te bouwen met een personage naar keuze.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Wat ga je maken
  - title: Het thema van je wereld
  - title: Bediening voor je speler
    completion:
      - engaged
  - title: Bouw een landschap
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Delen
  - title: Wat kun je verder nog doen?
