---
title: World builder
hero_image: images/banner.png
description: Design and build a 3D world with interesting scenery and features with
  a player character of your choice
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Theme your world
- title: Player controls
  completion:
  - engaged
- title: Build scenery
  completion:
  - internal
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
  - external
- title: Upgrade your project
- title: Share
- title: What next?
