---
title: World builder
hero_image: images/banner.png
description: Design and build a 3D world with interesting scenery and features with
  a player character of your choice
meta_title: Learn Unity | Game development | World builder
meta_description: Learn Unity game development with the Raspberry Pi Foundation. Use your Unity skills to design and build a 3D world with a player character of your choice.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: You will make
  - title: Theme your world
  - title: Player controls
    completion:
      - engaged
  - title: Build scenery
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: Share